[package]
name = "proto_gen"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
protobuf = "3.7.1"

serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"

[build-dependencies]
protobuf-codegen = "3.7.1"
protobuf = "3.7.1"
